# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "eq2_tiler"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter Menke"]
  s.date = "2011-11-20"
  s.description = "This is a map tile generator that uses rmagick to generate sets of map tiles for browser games on the basis of a simple DSL that describes how to layout the tiles."
  s.email = "pmenke@googlemail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/eq2.rb",
    "lib/eq2/eorath.rb",
    "lib/eq2/eorath/eorath_tile_maker.rb",
    "lib/eq2/tiler.rb",
    "lib/eq2/tiler/base_tile.rb",
    "lib/eq2/tiler/map_tile.rb",
    "lib/eq2/tiler/tile_bundle.rb",
    "lib/eq2_tiler.rb",
    "resources/tiler/ground-base.png",
    "resources/tiler/overlay-grass.png",
    "test/helper.rb",
    "test/test_eq2-tiler.rb",
    "test/test_generate_base_tile.rb",
    "test/test_tile_dsl.rb"
  ]
  s.homepage = "http://github.com/pmenke/eq2-tiler"
  s.licenses = ["CC"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "A customizable browser game map tile generator, based on rmagick"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rmagick>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rmagick>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rmagick>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

